# This file defines the uv workspace.
# It is not a buildable package.

[tool.uv]
workspace = { members = ["services/*", "shared/core", "shared/services"] }

[dependency-groups]
dev = [
    "fastapi>=0.116.1",
    "openai>=1.97.1",
    "python-dotenv>=1.1.1",
    "requests>=2.32.4",
    "slack-sdk>=3.36.0",
    "supabase>=2.17.0",
    "uvicorn>=0.35.0",
]
